x-anysync-daemon: &anysync-daemon
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: ${ANY_SYNC_DAEMONS_MEMORY_LIMIT:-500M}

x-anysync-node: &anysync-node
  <<: *anysync-daemon
  image: "ghcr.io/anyproto/any-sync-node:${ANY_SYNC_NODE_VERSION}"
  depends_on:
    any-sync-coordinator:
      condition: service_started

services:
  mongo-1:
    image: "mongo:${MONGO_VERSION}"
    restart: unless-stopped
    command: ["--replSet", "${MONGO_REPLICA_SET}", "--port", "${MONGO_1_PORT}"]
    volumes:
      - type: bind
        source: ./storage/mongo-1
        target: /data/db
        bind:
          create_host_path: true
    healthcheck:
      test: test $$(mongosh --port ${MONGO_1_PORT} --quiet --eval "try {rs.initiate({_id:'${MONGO_REPLICA_SET}',members:[{_id:0,host:\"mongo-1:${MONGO_1_PORT}\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
    ports:
      - "127.0.0.1:${MONGO_1_PORT}:${MONGO_1_PORT}"

  redis:
    image: "redis/redis-stack-server:${REDIS_VERSION}"
    restart: unless-stopped
    command: ["redis-server", "--port", "${REDIS_PORT}", "--dir", "/data/", "--appendonly", "yes", "--maxmemory", "${REDIS_MAXMEMORY}", "--maxmemory-policy", "noeviction", "--protected-mode", "no", "--loadmodule", "/opt/redis-stack/lib/redisbloom.so"]
    volumes:
      - type: bind
        source: ./storage/redis
        target: /data
        bind:
          create_host_path: true
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "-p", "${REDIS_PORT}", "ping" ]
      interval: 10s
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"

  minio:
    image: "minio/minio:${MINIO_VERSION}"
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":${MINIO_WEB_PORT}", "--address", ":${MINIO_PORT}"]
    environment:
      MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - type: bind
        source: ./storage/minio
        target: /data
        bind:
          create_host_path: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
      interval: 10s
    ports:
      - "127.0.0.1:${MINIO_PORT}:${MINIO_PORT}"
      - "${EXTERNAL_MINIO_WEB_PORT:-127.0.0.1:9001}:${MINIO_WEB_PORT}"

  create-bucket:
    depends_on:
      minio:
        condition: service_healthy
    image: "minio/mc:latest"
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:${MINIO_PORT} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      exit 0;
      "

any-sync-coordinator:
    <<: *anysync-daemon
    depends_on:
      mongo-1:
        condition: service_healthy
    image: "ghcr.io/anyproto/any-sync-coordinator:${ANY_SYNC_COORDINATOR_VERSION}"
    ports:
      - "${ANY_SYNC_COORDINATOR_PORT}:${ANY_SYNC_COORDINATOR_PORT}"
      - "${ANY_SYNC_COORDINATOR_QUIC_PORT}:${ANY_SYNC_COORDINATOR_QUIC_PORT}/udp"
    volumes:
      - type: bind
        source: /opt/anyproto/etc/any-sync-coordinator.yml
        target: /etc/any-sync/config.yml
        read_only: true
      - type: bind
        source: ./storage/networkstore/any-sync-coordinator
        target: /var/lib/any-sync-coordinator
        bind:
          create_host_path: true

  any-sync-filenode:
    <<: *anysync-daemon
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      any-sync-coordinator:
        condition: service_started
    image: "ghcr.io/anyproto/any-sync-filenode:${ANY_SYNC_FILENODE_VERSION}"
    ports:
      - "${ANY_SYNC_FILENODE_PORT}:${ANY_SYNC_FILENODE_PORT}"
      - "${ANY_SYNC_FILENODE_QUIC_PORT}:${ANY_SYNC_FILENODE_QUIC_PORT}/udp"
    volumes:
      - type: bind
        source: /opt/anyproto/etc/any-sync-filenode.yml
        target: /etc/any-sync/config.yml
        read_only: true
      - type: bind
        source: ./storage/networkstore/any-sync-filenode
        target: /var/lib/any-sync-filenode
        bind:
          create_host_path: true

  any-sync-consensusnode:
    <<: *anysync-daemon
    depends_on:
      any-sync-coordinator:
        condition: service_started
    image: "ghcr.io/anyproto/any-sync-consensusnode:${ANY_SYNC_CONSENSUSNODE_VERSION}"
    ports:
      - "${ANY_SYNC_CONSENSUSNODE_PORT}:${ANY_SYNC_CONSENSUSNODE_PORT}"
      - "${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}:${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}/udp"
    volumes:
      - type: bind
        source: /opt/anyproto/etc/any-sync-consensusnode.yml
        target: /etc/any-sync/config.yml
        read_only: true
      - type: bind
        source: ./storage/networkstore/any-sync-consensusnode
        target: /var/lib/any-sync-consensusnode
        bind:
          create_host_path: true

  any-sync-node-1:
    <<: *anysync-node
    ports:
      - "${ANY_SYNC_NODE_1_PORT}:${ANY_SYNC_NODE_1_PORT}"
      - "${ANY_SYNC_NODE_1_QUIC_PORT}:${ANY_SYNC_NODE_1_QUIC_PORT}/udp"
    volumes:
      - type: bind
        source: /opt/anyproto/etc/any-sync-node-1.yml
        target: /etc/any-sync/config.yml
        read_only: true
      - type: bind
        source: ./storage/networkstore/any-sync-node-1
        target: /var/lib/any-sync-node
        bind:
          create_host_path: true

  any-sync-node-2:
    <<: *anysync-node
    ports:
      - "${ANY_SYNC_NODE_2_PORT}:${ANY_SYNC_NODE_2_PORT}"
      - "${ANY_SYNC_NODE_2_QUIC_PORT}:${ANY_SYNC_NODE_2_QUIC_PORT}/udp"
    volumes:
      - type: bind
        source: /opt/anyproto/etc/any-sync-node-2.yml
        target: /etc/any-sync/config.yml
        read_only: true
      - type: bind
        source: ./storage/networkstore/any-sync-node-2
        target: /var/lib/any-sync-node
        bind:
          create_host_path: true

  any-sync-node-3:
    <<: *anysync-node
    ports:
      - "${ANY_SYNC_NODE_3_PORT}:${ANY_SYNC_NODE_3_PORT}"
      - "${ANY_SYNC_NODE_3_QUIC_PORT}:${ANY_SYNC_NODE_3_QUIC_PORT}/udp"
    volumes:
      - type: bind
        source: /opt/anyproto/etc/any-sync-node-3.yml
        target: /etc/any-sync/config.yml
        read_only: true
      - type: bind
        source: ./storage/networkstore/any-sync-node-3
        target: /var/lib/any-sync-node
        bind:
          create_host_path: true
